; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[activitystream][subdir] = "contrib"
projects[activitystream][version] = "3.0"

projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc4"

projects[auto_nodetitle][subdir] = "contrib"
projects[auto_nodetitle][version] = "1.0"

projects[backup_migrate][subdir] = "contrib"
projects[backup_migrate][version] = "2.4"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.2"

projects[context][subdir] = "contrib"
projects[context][version] = "3.0-beta6"

projects[devel][subdir] = contrib
projects[devel][version] = 1.3

projects[ds][subdir] = "contrib"
projects[ds][version] = "1.7"

projects[features][subdir] = contrib
projects[features][version] = 1.0

projects[features][subdir] = "contrib"
projects[features][version] = "1.0"

projects[filefield_paths][subdir] = "contrib"
projects[filefield_paths][version] = "1.0-beta3"

projects[filefield_sources][subdir] = "contrib"
projects[filefield_sources][version] = "1.7"

projects[google_analytics][subdir] = "contrib"
projects[google_analytics][version] = "1.3"

projects[libraries][subdir] = contrib
projects[libraries][version] = 1.0

projects[link][subdir] = "contrib"
projects[link][version] = "1.1"

projects[mandrill][subdir] = "contrib"
projects[mandrill][version] = "1.4"

projects[nodequeue][subdir] = contrib
projects[nodequeue][version] = 2.0-beta1

projects[omega_tools][subdir] = "contrib"
projects[omega_tools][version] = "3.0-rc4"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.3"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[quicktabs][subdir] = "contrib"
projects[quicktabs][version] = "3.4"

projects[switchtheme][subdir] = contrib
projects[switchtheme][version] = 1.0

projects[taxonomy_display][subdir] = "contrib"
projects[taxonomy_display][version] = "1.1"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[views][subdir] = "contrib"
projects[views][version] = "3.6"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"

projects[xmlsitemap][subdir] = "contrib"
projects[xmlsitemap][version] = "2.0-rc2"

; Base theme
=======
; Themes
projects[omega][version] = "3.1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[yarragreens_theme][download][type] = ""
projects[yarragreens_theme][download][url] = ""
projects[yarragreens_theme][type] = "theme"

; Libraries

projects[profiler][type] = libraries
projects[profiler][version] = 2.0-beta1

libraries[ckeditor][type] = libraries
libraries[ckeditor][download][type] = file
libraries[ckeditor][download][url] = http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.6.5/ckeditor_3.6.5.tar.gz

